export default data = [
  {
    name: 'Samsung Galaxy Z Flip',
    image: 'samsung',
    info: [
      {os: 'Android 10'},
      {size: '6.7 pulgadas'},
      {colors: '24 bits (16777216 colores)'},
      {price: '2.502,41€'},
      {memory: '8 GB'},
      {camera: '12 MP'},
    ],
    description: 'Información oficial sobre el nuevo smartphone plegable de gama alta Samsung Galaxy Z Flip presentado en febrero de 2020 a través de una ficha técnica con sus especificaciones, fotos, vídeo y precio. Este smartphone se caracteriza por su pantalla principal plegable de 6.7 pulgadas y su CPU Snapdragon 855+.',
  },
  {
    name: 'Apple iPhone 11',
    image: 'apple',
    info: [
      {os: 'iOS 13'},
      {size: '6.1 pulgadas'},
      {colors: '24 bits (16777216 colores)'},
      {price: '859,00€'},
      {memory: '4 GB'},
      {camera: '12 MP'}
    ],

    description: 'El nuevo iPhone 11 viene a ocupar el hueco dejado por el iPhone XR. Así se conoce al nuevo smartphone «barato» de Apple presentado en septiembre de 2019 y que como principales características tiene una doble cámara trasera, batería de larga duración, pantalla IPS de más de 6 pulgadas y el mismo chipset que sus hermanos mayores, un A13 Bionic. ',
  },
  {
    name: 'Huawei P40 Lite',
    image: 'huawei',
    info: [
      {os: 'Android 10'},
      {size: '6.4 pulgadas'},
      {colors: '24 bits (16777216 colores)'},
      {price: '408,18€'},
      {memory: '8 GB'},
      {camera: '48 MP'},
    ],
    description: 'Este teléfono inteligente destaca por su pantalla de 6.4 pulgadas, su CPU Kirrin 810 y su cámara posterior cuádruple de 48 MP + 8 MP + 2 MP + 2 MP.',
  },
  {
    name: 'Xiaomi Mi 10 Pro',
    image: 'xiaomi',
    info: [
      {os: 'Android 10'},
      {size: '6.67 pulgadas'},
      {colors: '24 bits (16777216 colores)'},
      {price: '523,00€'},
      {memory: '12 GB'},
      {camera: '20 MP'},
    ],
    description: 'El nuevo teléfono de la marca china llega al mercado presumiendo de 3 factores: Una cámara cuádruple con sensor de 108 MP que se ha convertido en la mejor de DxOMark en febrero de 2020, una batería con carga rápida de 50W y el procesador Snapdragon 865 acompañado de una GPU Adreno 650 bajo el capó.',
  },
  {
    name: 'Oppo A31',
    image: 'oppo',
    info: [
      {os: 'Android 9 Pie'},
      {size: '6.5 pulgadas'},
      {colors: '24 bits (16777216 colores)'},
      {price: '---€'},
      {memory: '4 GB'},
      {camera: '12 MP'},
    ],
    description: 'Oppo es una de las marcas que más esfuerzos está llevando a cabo por renovar su catálogo de teléfonos en los últimos meses. Este OPPO A31 es el enésimo ejemplo de móvil de gama media que llega al mercado presumiendo de una cámara triple com ose principal característica.',
  },
  {
    name: 'Alcatel 3L',
    image: 'alcatel',
    info: [
      {os: 'Android 10'},
      {size: '6.22 pulgadas'},
      {colors: '24 bits (16777216 colores)'},
      {price: '105,83€'},
      {memory: '4 GB'},
      {camera: '48 MP'},
    ],
    description: 'La apuesta de Alcatel para encabezar su catálogo de móviles buenos y baratos de cara al nuevo año que empieza es un Alcatel 3L que destaca por lucir detalles como tres cámaras traseras, con una lente de 48 Mpx a la cabeza, que nos ofrecerá el maximo detalle y luminosidad. ',
  },
  {
    name: 'Motorola One Hyper',
    image: 'motorola',
    info: [
      {os: 'Android 10'},
      {size: '6.5 pulgadas'},
      {colors: '24 bits (16777216 colores)'},
      {price: '200,00€'},
      {memory: '4 GB'},
      {camera: '64 MP'},
    ],
    description: 'El Motorola One Hyper es un smartphone presentado cuando el año 2019 daba sus últimos coletazos. Englobado en la clase medio alta, se trata del último modelo de la gama One del fabricante y se caracteriza por su pantalla de más de 6 pulgadas asnillos como por ser el primer teléfono de Motorola que trabaja con un módulo de cámara emergente.',
  },
  {
    name: 'LG W10 Alpha',
    image: 'lg',
    info: [
      {os: 'Android 9 Pie'},
      {size: '5.7 pulgadas'},
      {colors: '24 bits (16777216 colores)'},
      {price: '---€'},
      {memory: '3 GB'},
      {camera: '8 MP'},
    ],
    description: 'LG vuelve a aprovechar los días anteriores a la celebración de un MWC que en 2020 no se celebra para mostrar en sociedad algunos de sus nuevos smartphones. El más barato de todos ellos es este LG W10 Alpha que llega con características más que comedidas pero teniendo claro que es un smartphone de entrada enfocado a presupuestos más humildes.',
  },
  {
    name: 'Honor View30 Pro',
    image: 'honor',
    info: [
      {os: 'Android 10'},
      {size: '6.57 pulgadas'},
      {colors: '24 bits (16777216 colores)'},
      {price: '502,41€'},
      {memory: '8 GB'},
      {camera: '40 MP'},
    ],
    description: 'Este nuevo modelo viene con una pantalla de grandes dimensiones de 6.57 pulgadas y resolución FullHD+. En cuanto al almacenamiento interno viene con versiones de 128 GB o 256 GB acompañados de 8 GB de RAM y un procesador Kirin 990.',
  },
];